services:
  uptime-kuma:
    image: mattipaksula/uptime-kuma:3s
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
